openapi: 3.0.3
info:
  title: OpenAPI schema for RabbitMQ template .
components:
  schemas:
    variables:
      type: object
      properties:
        release_name:
          title: Release Name
          type: string
          description: The name of the Helm release.
          default: rabbitmq
          x-walrus-ui:
            group: Basic
            order: 2
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: rabbit-mq
          x-walrus-ui:
            group: Basic
            order: 3
        chart_version:
          title: Chart Version
          type: string
          description: The version of the ingress-nginx Helm chart.
          default: 15.0.1
          x-walrus-ui:
            group: Basic
            order: 4
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the RabbitMQ Helm release.
          default:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 256Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        username:
          title: Username
          type: string
          description: Username for RabbitMQ
          default: admin
          x-walrus-ui:
            group: Basic
            order: 6
        password:
          title: Password
          type: string
          description: Password for RabbitMQ
          default: ""
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 7
        domain_name:
          title: Domain Name
          type: string
          description: Domain name for RabbitMQ, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 8
        issuer_name:
          title: Issuer Name
          type: string
          description: Origin issuer name
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 9
        issuer_kind:
          title: Issuer Kind
          type: string
          description: Origin issuer kind
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 10
      x-walrus-ui:
        groupOrder:
        - Basic
